server:
  port: 8080

spring:
  application:
    name: cloud-demo-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/scloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    druid:
      validation-query: SELECT 1
      validation-query-timeout: 1800

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.henucg.entity

# 输出执行SQL
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
