server:
  port: 83

spring:
  application:
    name: cloudalibaba-consumer-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server-url:
  nacos-user-service: http://cloudalibaba-provider-payment-service