server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 此处开启，客户端开启的服务端降级：fallback = PaymentFallbackService.class 才会生效
feign:
  hystrix:
    enabled: true